# Site settings
title: Ryle Radio docs
description: Basic documentation for Ryle Radio
url: "https://ryle-e.github.io/ryle-radio-docs" # the base hostname & protocol for your site

logo: "/Images\ryleradiologo_color_small.png"
favicon: "/Images\ryleradiologo_color_small.ico"

nav_enabled: true
heading_anchors: true

# search settings
search_enabled: true

# aux links settings
aux_links:
  "Source documentation":
  - "https://ryle-e.github.io/ryle-radio-docs-scripting"

aux_links_new_tab:true

# Build settings
markdown: gfm
theme: just-the-docs # Replace with your chosen theme, e.g., jekyll-theme-cayman
color_scheme: dark
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
